"""Test testa

Revision ID: 5045b4e60723
Revises: dd35c51b0cbe
Create Date: 2023-04-15 15:21:46.231784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5045b4e60723'
down_revision = 'dd35c51b0cbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
