"""Title 4

Revision ID: 725a49ded14c
Revises: 8bb1afd77b02
Create Date: 2023-04-14 22:57:59.616763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '725a49ded14c'
down_revision = '8bb1afd77b02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
