"""Title 3

Revision ID: 8bb1afd77b02
Revises: 64513a9bd395
Create Date: 2023-04-14 22:54:26.700111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bb1afd77b02'
down_revision = '64513a9bd395'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
