"""Test testa

Revision ID: dd35c51b0cbe
Revises: f5182897a525
Create Date: 2023-04-15 15:12:42.969619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd35c51b0cbe'
down_revision = 'f5182897a525'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
